# Generated by Django 5.2.13 on 2026-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_recurringtask_integration_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('note', 'Nota'), ('receipt', 'Comprobante'), ('warranty', 'Garantia'), ('manual', 'Manual'), ('other', 'Otro')], default='note', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('entity_type', models.CharField(choices=[('product', 'Producto'), ('fixed_expense', 'Gasto fijo'), ('recurring_task', 'Tarea recurrente'), ('general', 'General')], default='general', max_length=30)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Desayuno'), ('lunch', 'Almuerzo'), ('dinner', 'Cena'), ('snack', 'Merienda')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_mealplan',
                'ordering': ['date', 'meal_time'],
                'unique_together': {('date', 'meal_time')},
            },
        ),
    ]
