# Generated by Django 5.2.13 on 2026-05-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_document_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='linked_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='household.mealplan'),
        ),
    ]
